from django.urls import path, include
<<<<<<< HEAD
from account.views import UserRegisterationView,UserLoginView,UserProfileView, UserChangePasswordView, SendPasswordResetEmailView, UserPasswordResetView, UserLogoutView,send_message
=======
from rest_framework.routers import DefaultRouter
from account.views import UserRegisterationView,UserLoginView,UserProfileView, UserChangePasswordView, SendPasswordResetEmailView, UserPasswordResetView, UserLogoutView,EventViewSet


# Created a router for the EventViewSet
router = DefaultRouter()
router.register(r'event', EventViewSet, basename='event')
>>>>>>> 100e2a8bb02581432211bf3d7c052188edbe8318
urlpatterns = [
    path('register/', UserRegisterationView.as_view(),name='register'),
    path('login/', UserLoginView.as_view(),name='login'),
    path('profile/', UserProfileView.as_view(),name='profile'),
    path('changepassword/', UserChangePasswordView.as_view(),name='changepassword'),
    path('send-reset-password-email/', SendPasswordResetEmailView.as_view(),name='send_password_reset_email'),
    path('reset-password/<uid>/<token>/',UserPasswordResetView.as_view(),name='password_reset'),
<<<<<<< HEAD
    path('send_message/',send_message,name="send_message"),
    path('logout/',UserLogoutView.as_view(),name='logout')
]
=======
    path('logout/',UserLogoutView.as_view(),name='logout'),
  
    #    the event-related URLs generated by the router under the "/api/" endpoint
    path('api/', include(router.urls))
    ]
#Here are the endpoints for EventViewSet:

# List events: /api/events/ (GET)
# Create a new event: /api/events/ (POST) - Only accessible to admin users due to the IsAdminOrReadOnly permission.
# Retrieve a specific event: /api/events/{id}/ (GET)
# Update a specific event: /api/events/{id}/ (PUT, PATCH, DELETE) - Only accessible to admin users due to the IsAdminOrReadOnly permission.
>>>>>>> 100e2a8bb02581432211bf3d7c052188edbe8318
